"""MT103 -> ISO 20022 pacs.008.001.08 mapper with per-element lineage."""
import re
import uuid
import hashlib
import datetime as dt
from dataclasses import dataclass, field
from decimal import Decimal
from typing import List, Optional
from lxml import etree

from .models import (Finding, Lineage, Party, DIRECT, CODE, PARSED, INFERRED, FREETEXT,
                     WARNING, INFO, ADDRESS, INFERENCE, DATA_LOSS, ENRICHMENT)
from .mt103 import MT103, parse_party
from .addrparse import parse_address, AddrResult
from .refdata import CURRENCIES, IBAN_LENGTHS

NS = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08"
CHRG = {"OUR": "DEBT", "BEN": "CRED", "SHA": "SHAR"}


@dataclass
class Conversion:
    msg_id: str
    xml: Optional[bytes]
    lineage: List[Lineage] = field(default_factory=list)
    findings: List[Finding] = field(default_factory=list)   # mapper-side observations
    addr_stats: dict = field(default_factory=dict)


def _q(tag: str) -> str:
    return "{%s}%s" % (NS, tag)


def _amt(text: str, ccy: str) -> str:
    t = text.strip().replace(",", ".")
    t = t[:-1] if t.endswith(".") else t
    d = Decimal(t)
    dec = max(CURRENCIES.get(ccy, 2), -d.as_tuple().exponent)
    return f"{d:.{dec}f}"


def _uetr_from(msg_id: str) -> str:
    return str(uuid.UUID(bytes=hashlib.md5(("uetr:" + msg_id).encode()).digest(), version=4))


class _Builder:
    def __init__(self, msg_id: str):
        self.msg_id = msg_id
        self.lineage: List[Lineage] = []
        self.findings: List[Finding] = []

    def path(self, e) -> str:
        parts = []
        while e is not None:
            parts.append(etree.QName(e).localname)
            e = e.getparent()
        parts = [p for p in reversed(parts) if p not in ("Document", "FIToFICstmrCdtTrf")]
        return "/".join(parts)

    def sub(self, parent, tag, text=None, src=None, method=None, **attrs):
        e = etree.SubElement(parent, _q(tag))
        for k, v in attrs.items():
            e.set(k, v)
        if text is not None:
            e.text = text
            self.lineage.append(Lineage(self.path(e), src or "", method or DIRECT))
        return e

    def note(self, rule, cat, sev, path, msg):
        self.findings.append(Finding(self.msg_id, rule, cat, sev, path, msg))


def convert(mt: MT103, now: Optional[dt.datetime] = None) -> Conversion:
    if mt.fatal:
        return Conversion(mt.msg_id, None)
    now = now or dt.datetime.now(dt.timezone.utc).replace(microsecond=0)
    b = _Builder(mt.msg_id)
    root = etree.Element(_q("Document"), nsmap={None: NS})
    msg = etree.SubElement(root, _q("FIToFICstmrCdtTrf"))

    # ---------------- Group header ----------------
    gh = b.sub(msg, "GrpHdr")
    b.sub(gh, "MsgId", mt.get("20").strip(), ":20:", DIRECT)
    b.sub(gh, "CreDtTm", now.strftime("%Y-%m-%dT%H:%M:%S") + "Z", "conversion time", INFERRED)
    b.sub(gh, "NbOfTxs", "1", "structure", INFERRED)
    si = b.sub(gh, "SttlmInf")
    t53, t54 = mt.get("53A"), mt.get("54A")
    b.sub(si, "SttlmMtd", "INGA" if t53 and not t54 else "INDA", ":53A:/:54A: presence", INFERRED)
    if t53:
        p53 = parse_party("53A", t53)
        a = b.sub(si, "InstgRmbrsmntAgt"); f = b.sub(a, "FinInstnId")
        b.sub(f, "BICFI", p53.bic, ":53A:", DIRECT)
    if t54:
        p54 = parse_party("54A", t54)
        a = b.sub(si, "InstdRmbrsmntAgt"); f = b.sub(a, "FinInstnId")
        b.sub(f, "BICFI", p54.bic, ":54A:", DIRECT)

    # ---------------- Transaction ----------------
    tx = b.sub(msg, "CdtTrfTxInf")
    # remittance split (also yields /ROC/ end-to-end reference)
    unstructured, inv, rfb, roc = _split_70(mt.get("70"))

    pid = b.sub(tx, "PmtId")
    b.sub(pid, "InstrId", mt.get("20").strip(), ":20:", DIRECT)
    if roc:
        b.sub(pid, "EndToEndId", roc[:35], ":70: /ROC/", CODE)
    else:
        b.sub(pid, "EndToEndId", "NOTPROVIDED", "no /ROC/ in :70:", INFERRED)
    b.sub(pid, "TxId", mt.get("20").strip(), ":20:", DIRECT)
    if mt.uetr:
        b.sub(pid, "UETR", mt.uetr, "{3:{121:}}", DIRECT)
    else:
        b.sub(pid, "UETR", _uetr_from(mt.msg_id), "generated by translator", INFERRED)
        b.note("INF_UETR_GENERATED", INFERENCE, WARNING, "CdtTrfTxInf/PmtId/UETR",
               "MT103 carries no UETR; a new one was minted, so the payment cannot be tracked end-to-end")

    op = mt.get("23B").strip()
    if op in ("SPRI", "SSTD", "SPAY"):
        pt = b.sub(tx, "PmtTpInf"); sl = b.sub(pt, "SvcLvl")
        b.sub(sl, "Prtry", op, ":23B:", CODE)

    b.sub(tx, "IntrBkSttlmAmt", _amt(mt.amount, mt.ccy), ":32A:", DIRECT, Ccy=mt.ccy)
    b.sub(tx, "IntrBkSttlmDt", mt.value_date.isoformat(), ":32A:", DIRECT)
    f33 = mt.get("33B")
    if f33 and re.match(r"^[A-Z]{3}\d", f33.strip()):
        c, a_ = f33.strip()[:3], f33.strip()[3:]
        b.sub(tx, "InstdAmt", _amt(a_, c), ":33B:", DIRECT, Ccy=c)
    f36 = mt.get("36")
    if f36 and re.match(r"^\d", f36.strip()):
        b.sub(tx, "XchgRate", f36.strip().replace(",", "."), ":36:", DIRECT)
    b.sub(tx, "ChrgBr", CHRG[mt.get("71A").strip()], ":71A:", CODE)
    for tag, who in (("71F", mt.sender_bic), ("71G", mt.receiver_bic)):
        for v in mt.all(tag):
            v = v.strip()
            if not re.match(r"^[A-Z]{3}\d", v):
                continue
            ci = b.sub(tx, "ChrgsInf")
            b.sub(ci, "Amt", _amt(v[3:], v[:3]), f":{tag}:", DIRECT, Ccy=v[:3])
            ag = b.sub(ci, "Agt"); fi = b.sub(ag, "FinInstnId")
            b.sub(fi, "BICFI", who, f"{tag}: agent not stated; header BIC assumed", INFERRED)
            b.note("INF_CHRG_AGENT_INFERRED", INFERENCE, INFO, "CdtTrfTxInf/ChrgsInf/Agt",
                   f":{tag}: does not say which bank levied the charge; {who} was assumed")

    # Instructing / instructed agents come from the FIN envelope
    ia = b.sub(tx, "InstgAgt"); fi = b.sub(ia, "FinInstnId"); b.sub(fi, "BICFI", mt.sender_bic, "{1:} sender LT", DIRECT)
    ta = b.sub(tx, "InstdAgt"); fi = b.sub(ta, "FinInstnId"); b.sub(fi, "BICFI", mt.receiver_bic, "{2:} receiver LT", DIRECT)

    if mt.get("56A") or mt.get("56D"):
        tag56 = "56A" if mt.get("56A") else "56D"
        _agent(b, tx, "IntrmyAgt1", parse_party(tag56, mt.get(tag56)), tag56)

    # ---------------- Debtor ----------------
    t50 = mt.first_tag(["50A", "50F", "50K"])
    dbtr = parse_party(t50, mt.get(t50))
    _party(b, tx, "Dbtr", dbtr, t50, mt.msg_id)
    _account(b, tx, "DbtrAcct", dbtr.account, t50)

    # Debtor agent
    t52 = mt.first_tag(["52A", "52D"])
    if t52:
        _agent(b, tx, "DbtrAgt", parse_party(t52, mt.get(t52)), t52)
    else:
        da = b.sub(tx, "DbtrAgt"); fi = b.sub(da, "FinInstnId")
        b.sub(fi, "BICFI", mt.sender_bic, ":52a: absent; sender BIC assumed", INFERRED)
        b.note("INF_DBTRAGT_INFERRED", INFERENCE, INFO, "CdtTrfTxInf/DbtrAgt",
               "No :52a: ordering institution; the sending bank was assumed to be the debtor agent")
    # Creditor agent
    t57 = mt.first_tag(["57A", "57D"])
    if t57:
        _agent(b, tx, "CdtrAgt", parse_party(t57, mt.get(t57)), t57)
    else:
        ca = b.sub(tx, "CdtrAgt"); fi = b.sub(ca, "FinInstnId")
        b.sub(fi, "BICFI", mt.receiver_bic, ":57a: absent; receiver BIC assumed", INFERRED)
        b.note("INF_CDTRAGT_INFERRED", INFERENCE, INFO, "CdtTrfTxInf/CdtrAgt",
               "No :57a: account-with institution; the receiving bank was assumed to be the creditor agent")

    # ---------------- Creditor ----------------
    t59 = mt.first_tag(["59", "59A", "59F"])
    cdtr = parse_party(t59, mt.get(t59))
    _party(b, tx, "Cdtr", cdtr, t59, mt.msg_id)
    _account(b, tx, "CdtrAcct", cdtr.account, t59)

    # ---------------- Narrative blocks ----------------
    for line in (mt.get("72") or "").split("\n"):
        if line.strip():
            n = b.sub(tx, "InstrForNxtAgt")
            b.sub(n, "InstrInf", line.strip(), ":72:", FREETEXT)
    for line in (mt.get("77B") or "").split("\n"):
        if line.strip():
            r = b.sub(tx, "RgltryRptg"); d = b.sub(r, "Dtls")
            b.sub(d, "Inf", line.strip()[:35], ":77B:", FREETEXT)

    if unstructured or inv or rfb:
        rm = b.sub(tx, "RmtInf")
        if unstructured:
            txt = " ".join(unstructured)
            chunks = [txt[:140]] + ([txt[140:280]] if len(txt) > 140 else [])
            for c in chunks:
                b.sub(rm, "Ustrd", c, ":70:", FREETEXT)
        if inv or rfb:
            st = b.sub(rm, "Strd")
            if inv:
                rd = b.sub(st, "RfrdDocInf"); tp = b.sub(rd, "Tp"); co = b.sub(tp, "CdOrPrtry")
                b.sub(co, "Cd", "CINV", ":70: /INV/", CODE)
                b.sub(rd, "Nb", inv[:35], ":70: /INV/", CODE)
                b.note("GAIN_STRUCT_RMT", ENRICHMENT, INFO, "CdtTrfTxInf/RmtInf/Strd/RfrdDocInf",
                       "Invoice number recovered from /INV/ code word into a structured, machine-readable element")
            if rfb:
                cr = b.sub(st, "CdtrRefInf")
                b.sub(cr, "Ref", rfb[:35], ":70: /RFB/", CODE)
                b.note("GAIN_STRUCT_RMT", ENRICHMENT, INFO, "CdtTrfTxInf/RmtInf/Strd/CdtrRefInf",
                       "Beneficiary reference recovered from /RFB/ code word into a structured element")
    return Conversion(mt.msg_id, etree.tostring(root, pretty_print=True, xml_declaration=True, encoding="UTF-8"),
                      b.lineage, b.findings, _addr_stats(b))


def _addr_stats(b: _Builder) -> dict:
    out = {}
    for l in b.lineage:
        if "PstlAdr" in l.path:
            role = l.path.split("/")[1]
            out.setdefault(role, []).append((l.path.split("/")[-1], l.method))
    return out


def _split_70(v: Optional[str]):
    if not v:
        return [], None, None, None
    uns, inv, rfb, roc = [], None, None, None
    for line in v.split("\n"):
        m = re.match(r"^/(INV|RFB|ROC|IPI)/(.*)$", line)
        if m and m.group(2).strip():
            code = m.group(1)
            parts = m.group(2).strip().split(None, 1)
            val = parts[0]
            if len(parts) > 1:               # text after the reference stays narrative
                uns.append(parts[1])
            if code == "INV" and inv is None:
                inv = val
            elif code == "RFB" and rfb is None:
                rfb = val
            elif code == "ROC" and roc is None:
                roc = val
            else:
                uns.append(line.strip())
        elif line.strip():
            uns.append(line.strip())
    return uns, inv, rfb, roc


_IBAN_SHAPE = re.compile(r"^[A-Z]{2}\d{2}[A-Za-z0-9]{1,30}$")


def _account(b, tx, tag, acct, src):
    if not acct:
        return
    a = b.sub(tx, tag); i = b.sub(a, "Id")
    if _IBAN_SHAPE.match(acct) and acct[:2] in IBAN_LENGTHS:
        b.sub(i, "IBAN", acct, f":{src}: account line", DIRECT)
    else:
        o = b.sub(i, "Othr")
        b.sub(o, "Id", acct[:34], f":{src}: account line", DIRECT)


def _agent(b, tx, tag, p: Party, src):
    ag = b.sub(tx, tag); fi = b.sub(ag, "FinInstnId")
    if p.bic:
        b.sub(fi, "BICFI", p.bic, f":{src}:", DIRECT)
    elif p.name_lines:
        b.sub(fi, "Nm", p.name_lines[0][:140], f":{src}: line 1", DIRECT)
        _address(b, fi, p.name_lines[1:], f":{src}:", tag)


def _party(b, tx, tag, p: Party, src, msg_id):
    pe = b.sub(tx, tag)
    if p.option == "A":
        pid = b.sub(pe, "Id"); org = b.sub(pid, "OrgId")
        b.sub(org, "AnyBIC", p.bic, f":{src}:", DIRECT)
        return
    if p.option == "F":
        names = p.struct.get("1", [])
        if names:
            b.sub(pe, "Nm", " ".join(names)[:140], f":{src}: 1/", DIRECT)
        addr_lines = p.struct.get("2", [])
        town_cc = p.struct.get("3", [])
        res = AddrResult()
        if town_cc:
            m = re.match(r"^([A-Z]{2})/(.*)$", town_cc[0])
            if m:
                res.ctry, res.town = m.group(1), m.group(2).strip()
        extra = parse_address(addr_lines)
        res.street, res.bldg, res.lines = extra.street, extra.bldg, extra.lines
        _emit_addr(b, pe, res, f":{src}: 2/,3/", tag, from_f=True)
        dropped = [k for k in ("4", "5", "6", "7", "8") if k in p.struct]
        if dropped:
            b.note("DL_UNMAPPED_50F_LINES", DATA_LOSS, WARNING, f"CdtTrfTxInf/{tag}",
                   f"Structured lines {', '.join(d + '/' for d in dropped)} (birth data / IDs / extra info) have no mapping in this toolkit and were not carried")
        return
    # K / no option free text
    if p.name_lines:
        b.sub(pe, "Nm", p.name_lines[0][:140], f":{src}: line 1", DIRECT)
        if len(p.name_lines[0]) == 35:
            b.note("DL_NAME_TRUNC_SUSPECT", DATA_LOSS, WARNING, f"CdtTrfTxInf/{tag}/Nm",
                   "Name fills the whole 35-character MT line; the original legal name may already have been cut off upstream")
        _address(b, pe, p.name_lines[1:], f":{src}:", tag)


def _address(b, parent, lines, src, role):
    res = parse_address(lines)
    _emit_addr(b, parent, res, src, role)


def _emit_addr(b, parent, res: AddrResult, src, role, from_f=False):
    if not (res.street or res.bldg or res.pstcd or res.town or res.subdiv or res.ctry or res.lines):
        return
    pa = b.sub(parent, "PstlAdr")
    base = DIRECT if from_f else PARSED
    if res.street: b.sub(pa, "StrtNm", res.street[:70], src, PARSED)
    if res.bldg: b.sub(pa, "BldgNb", res.bldg[:16], src, PARSED)
    if res.pstcd: b.sub(pa, "PstCd", res.pstcd[:16], src, PARSED)
    if res.town: b.sub(pa, "TwnNm", res.town[:35], src, base)
    if res.subdiv: b.sub(pa, "CtrySubDvsn", res.subdiv, src, PARSED)
    if res.ctry:
        b.sub(pa, "Ctry", res.ctry, src + (" country deduced from town" if res.ctry_inferred else ""),
              INFERRED if res.ctry_inferred else base)
        if res.ctry_inferred:
            b.note("INF_CTRY_FROM_TOWN", INFERENCE, WARNING, f"CdtTrfTxInf/{role}/PstlAdr/Ctry",
                   f"Country {res.ctry} was never stated; it was deduced from the town name '{res.town}' (may be wrong for namesake towns)")
    for l in res.lines:
        b.sub(pa, "AdrLine", l[:70], src, FREETEXT)
    if res.town and res.ctry and not res.ctry_inferred:
        b.note("GAIN_STRUCT_ADDR", ENRICHMENT, INFO, f"CdtTrfTxInf/{role}/PstlAdr",
               "Town and country extracted from free text into structured elements (CBPR+ hybrid-ready)")
